# Generated by Django 4.2.1 on 2023-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_alter_purchase_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company_name',
            field=models.CharField(blank=True, default='Null', max_length=100, null=True),
        ),
    ]
